services:

  statement-generator:
    image: ghcr.io/ardishan/ghr-statement-generator:latest
    container_name: statement-generator
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "${TAILSCALE_IP}:8501:8501"
      - "${LAN_IP}:8501:8501"
